name: Update packages

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - update_sh
  schedule:
    - cron: 30 21 * * * 
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04   
    #if: github.event.repository.owner.id == github.event.sender.id

    name: Build ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [packages,packages-19.07]
        
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/liuran001/openwrt-packages.git ${{matrix.target}}
        mkdir backup
        cp -rf ${{matrix.target}}/.git backup
        rm -rf ./${{matrix.target}}
        mv -f backup/.git ${{matrix.target}}
        rm -rf backup
        cd ${{matrix.target}}
        $GITHUB_WORKSPACE/${{matrix.target}}.sh

    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git config user.name "liuran001"
        git config user.email "liuran001@126.com"
        git add .
        git commit -m "update$(TZ='Asia/Shanghai' date +@%Y%m%d)"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/liuran001/openwrt-packages.git" HEAD:${{matrix.target}}
 
